docker/ubuntu/22.04: use superbuild

diff --git a/docker/ubuntu/22.04/xpu_ispc_build/Dockerfile b/docker/ubuntu/22.04/xpu_ispc_build/Dockerfile
--- a/docker/ubuntu/22.04/xpu_ispc_build/Dockerfile
+++ b/docker/ubuntu/22.04/xpu_ispc_build/Dockerfile
@@ -9,77 +9,54 @@ SHELL ["/bin/bash", "-c"]
 
 ARG REPO=ispc/ispc
 ARG SHA=main
-ARG LLVM_VERSION=16.0
 ARG IGC_VER=14062.11
-ARG L0L_VER=1.14.0
 ARG CR_VER=23.22.26516.18
 ARG CR_VER_SUFFIX=26516.18
-ARG VC_INTRINSICS_COMMIT_SHA="77f069b71fa9042bc4b2f68d06942a43c8ecec73"
-ARG SPIRV_TRANSLATOR_COMMIT_SHA="8703d43bd14d000fc630c2d3918d918819d23741"
+ARG LTO
 
 # !!! Make sure that your docker config provides enough memory to the container,
 # otherwise LLVM build may fail, as it will use all the cores available to container.
 
 # Packages
 RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -y clang-12 build-essential libnuma1 opencl-headers ocl-icd-libopencl1 clinfo vim gcc g++ git python3-dev imagemagick \
-    m4 bison flex libncurses-dev libtinfo-dev libc6-dev-i386 cpio lsb-core wget netcat-openbsd libtbb2-dev libglfw3-dev pkgconf gdb gcc-multilib g++-multilib curl ca-certificates cmake && \
+    m4 bison flex libncurses-dev libtinfo-dev libc6-dev-i386 cpio lsb-core wget netcat-openbsd libtbb2-dev libglfw3-dev pkgconf gdb gcc-multilib g++-multilib curl ca-certificates ninja-build && \
     rm -rf /var/lib/apt/lists/*
 
-WORKDIR /home/src
-
-RUN git clone https://github.com/$REPO.git ispc
-
-WORKDIR /home/src/ispc
-RUN git checkout $SHA
-ENV ISPC_HOME=/home/src/ispc
-
-# LLVM
-ENV LLVM_HOME=/home/tools/llvm
-RUN python3 ./alloy.py -b --version="$LLVM_VERSION" --selfbuild && \
-    rm -rf "$LLVM_HOME"/build-"$LLVM_VERSION" "$LLVM_HOME"/llvm-"$LLVM_VERSION" "$LLVM_HOME"/bin-"$LLVM_VERSION"_temp "$LLVM_HOME"/build-"$LLVM_VERSION"_temp
-
-WORKDIR /home/packages
+# Download and install required version of cmake (3.23.5 for both x86 and aarch64) as required for superbuild preset jsons.
+RUN if [[ $(uname -m) =~ "x86" ]]; then \
+        export CMAKE_URL="https://cmake.org/files/v3.23/cmake-3.23.5-linux-x86_64.sh"; \
+    else \
+        export CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-linux-aarch64.sh"; \
+    fi && \
+    wget -q --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5 $CMAKE_URL && \
+    sh cmake-*.sh --prefix=/usr/local --skip-license && rm -rf cmake-*.sh
 
 # Compute runtime
+# Install packages and clean up
 RUN wget -q --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5  https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.${IGC_VER}/intel-igc-core_1.0.${IGC_VER}_amd64.deb && \
     wget -q --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5  https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.${IGC_VER}/intel-igc-opencl_1.0.${IGC_VER}_amd64.deb && \
     wget -q --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5  https://github.com/intel/compute-runtime/releases/download/${CR_VER}/intel-level-zero-gpu-dbgsym_1.3.${CR_VER_SUFFIX}_amd64.ddeb && \
     wget -q --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5  https://github.com/intel/compute-runtime/releases/download/${CR_VER}/intel-level-zero-gpu_1.3.${CR_VER_SUFFIX}_amd64.deb && \
     wget -q --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5  https://github.com/intel/compute-runtime/releases/download/${CR_VER}/intel-opencl-icd-dbgsym_${CR_VER}_amd64.ddeb && \
     wget -q --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5  https://github.com/intel/compute-runtime/releases/download/${CR_VER}/intel-opencl-icd_${CR_VER}_amd64.deb && \
-    wget -q --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5  https://github.com/intel/compute-runtime/releases/download/${CR_VER}/libigdgmm12_22.3.0_amd64.deb
+    wget -q --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5  https://github.com/intel/compute-runtime/releases/download/${CR_VER}/libigdgmm12_22.3.0_amd64.deb && \
+    dpkg -i ./*.deb && \
+    rm ./*.deb
 
-# L0 loaader
-RUN wget -q --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5 https://github.com/oneapi-src/level-zero/releases/download/v${L0L_VER}/level-zero-devel_${L0L_VER}+u22.04_amd64.deb && \
-    wget -q --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5 https://github.com/oneapi-src/level-zero/releases/download/v${L0L_VER}/level-zero_${L0L_VER}+u22.04_amd64.deb
-
-# Install packages and clean up
-RUN dpkg -i ./*.deb
-WORKDIR /home
-RUN rm -rf packages
-
-# vc-intrinsics
 WORKDIR /home/src
-RUN git clone https://github.com/intel/vc-intrinsics.git
-WORKDIR /home/src/vc-intrinsics
-RUN git checkout $VC_INTRINSICS_COMMIT_SHA && mkdir -p build
-WORKDIR /home/src/vc-intrinsics/build
-RUN cmake -DLLVM_DIR=$LLVM_HOME/bin-$LLVM_VERSION/lib/cmake/llvm -DCMAKE_INSTALL_PREFIX=/home/deps -DPYTHON_EXECUTABLE=/usr/bin/python3 ../ && make install -j"$(nproc)"
+RUN git clone https://github.com/$REPO.git ispc
 
-# SPIRV Translator
-WORKDIR /home/src
-RUN git clone https://github.com/KhronosGroup/SPIRV-LLVM-Translator.git
-WORKDIR /home/src/SPIRV-LLVM-Translator
-RUN git checkout $SPIRV_TRANSLATOR_COMMIT_SHA && mkdir -p build
-WORKDIR /home/src/SPIRV-LLVM-Translator/build
-RUN cmake -DLLVM_DIR=$LLVM_HOME/bin-$LLVM_VERSION/lib/cmake/llvm/ -DCMAKE_INSTALL_PREFIX=/home/deps -DPYTHON_EXECUTABLE=/usr/bin/python3 ../ && make install -j"$(nproc)"
-
-# ISPC build
-ENV PATH=$LLVM_HOME/bin-$LLVM_VERSION/bin:$PATH
 WORKDIR /home/src/ispc
-RUN mkdir -p build
-WORKDIR /home/src/ispc/build
-RUN cmake -DXE_ENABLED=ON -DCMAKE_INSTALL_PREFIX=/home/ispc/ -DXE_DEPS_DIR=/home/deps ../ && make install -j"$(nproc)"
-RUN make check-all -j"$(nproc)"
-# Add ISPC to PATH
-ENV PATH=/home/ispc/bin:$PATH
+# Build Clang/LLVM, XE dependencies and then ISPC.
+RUN git checkout $SHA && \
+    cmake superbuild \
+        -B build \
+        --preset os \
+        -DLTO=$LTO \
+        -DINSTALL_ISPC=ON \
+        -DINSTALL_TOOLCHAIN=ON \
+        -DCMAKE_INSTALL_PREFIX=/usr/local && \
+    cmake --build build && \
+    (cmake --build build --target ispc-stage2-check-all || true) && \
+    mv build/build-ispc-stage2/src/ispc-stage2-build/*.tar.gz ./ && \
+    rm -rf build
